"""empty message

Revision ID: 7b19e556201d
Revises: 742779d326b3
Create Date: 2022-03-06 19:25:16.355863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b19e556201d'
down_revision = '742779d326b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_votes')
    op.add_column('votes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('votes', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.drop_constraint('votes_userId_fkey', 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'comments', ['comment_id'], ['id'])
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'])
    op.drop_column('votes', 'vote_count')
    op.drop_column('votes', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('votes', sa.Column('vote_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key('votes_userId_fkey', 'votes', 'users', ['userId'], ['id'])
    op.drop_column('votes', 'comment_id')
    op.drop_column('votes', 'user_id')
    op.create_table('comment_votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vote_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='comment_votes_comment_id_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='comment_votes_userId_fkey'),
    sa.PrimaryKeyConstraint('id', name='comment_votes_pkey')
    )
    # ### end Alembic commands ###
