"""empty message

Revision ID: a36ce5cdb1f8
Revises: e5ff112fd887
Create Date: 2022-05-24 15:27:50.105599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36ce5cdb1f8'
down_revision = 'e5ff112fd887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('community_name', sa.Text(), nullable=False))
    op.add_column('communities', sa.Column('community_description', sa.Text(), nullable=False))
    op.drop_constraint('communities_postId_fkey', 'communities', type_='foreignkey')
    op.drop_column('communities', 'postId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('postId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('communities_postId_fkey', 'communities', 'posts', ['postId'], ['id'])
    op.drop_column('communities', 'community_description')
    op.drop_column('communities', 'community_name')
    # ### end Alembic commands ###
