"""empty message

Revision ID: fc4a6fcc3f3c
Revises: 8d922eb3fbaa
Create Date: 2022-06-05 17:20:56.501106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4a6fcc3f3c'
down_revision = '8d922eb3fbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('community_type', sa.Text(), nullable=False))
    op.drop_column('communities', 'community_description')
    op.create_foreign_key(None, 'posts', 'communities', ['community_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.add_column('communities', sa.Column('community_description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('communities', 'community_type')
    # ### end Alembic commands ###
