"""add votes to posts

Revision ID: 3e87dcdf4f68
Revises: fc4a6fcc3f3c
Create Date: 2026-01-19 01:51:42.348600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e87dcdf4f68'
down_revision = 'fc4a6fcc3f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'votes')
    # ### end Alembic commands ###
