"""empty message

Revision ID: b26cc16982af
Revises: 7b19e556201d
Create Date: 2022-04-19 12:52:35.362079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26cc16982af'
down_revision = '7b19e556201d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parentId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'parentId')
    # ### end Alembic commands ###
