"""empty message

Revision ID: 953f1b5a4bb5
Revises: b26cc16982af
Create Date: 2022-04-30 13:14:56.690568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953f1b5a4bb5'
down_revision = 'b26cc16982af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('username', sa.Text(), nullable=True))
    op.add_column('votes', sa.Column('upvote', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'upvote')
    op.drop_column('posts', 'username')
    # ### end Alembic commands ###
