"""empty message

Revision ID: 8d922eb3fbaa
Revises: a36ce5cdb1f8
Create Date: 2022-05-24 16:46:46.640728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d922eb3fbaa'
down_revision = 'a36ce5cdb1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('community_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'community_id')
    # ### end Alembic commands ###
